### ISSUE TITLE
No Original / Default Theme included

### ISSUE THREAD

**Issue by leifclaesson** [FiercestT/EasyEdaThemes#15]
I am normally happy with the Original EasyEDA theme but needed to edit a document in a dark environment once, so I installed this extension and did the work.

Afterwards, I uninstalled the extension, but found the document _still kept the theme_, individually applied as a custom color on each element.

How can I remove the theme from my document and get the original colors back?

Reinstalling the extension does not help since there is no Default / Original color option.

Any help appreciated. I even tried comparing an original file to a themed file so that I could modify the file myself, but this was a dead end since the entire document is kept in a binary blob -- the JSON document is only a wrapper...

**Comment by FiercestT** [comment]
Hi!

You can set the built in EasyEDA view theme to original instead of custom, which will override the extension theme on the page. This can done even with the extension running (but changing the extension theme will override this setting).
![image](https://github.com/FiercestT/EasyEdaThemes/assets/46426125/787c9688-7533-4a9c-b1d6-5b77b8ef3423)

There are also some built in light themes at the bottom of the theme selector.

Also, you can create your own theme by adding one in `themes.json` and reinstalling the extension.

Let me know if this helps.

**Comment by leifclaesson** [comment]
Thank you very much for your fast response! That completely solves my problem. I had _no_ idea the View / Theme menu existed, I have never noticed it before!
